FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libz-dev libbz2-dev liblzma-dev libcurl3-dev build-essential automake git libncurses5-dev

RUN git clone --recursive https://github.com/samtools/htslib.git
WORKDIR /htslib
RUN autoreconf -i
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/htslib
RUN ldconfig

ADD . /repo
WORKDIR /repo
RUN autoreconf
RUN ./configure
RUN make -j8
